class CONSTANTES_ENTERAS {
	ALTA_EXITOSA = 2
	ALTA_FALLIDA = 3
	BAJA_EXITOSA = 4
	BAJA_FALLIDA = 5
	CAMBIO_EXITOSO = 6
	CAMBIO_FALLIDO = 7
	CONSULTA_EXITOSA = 1
	CONSULTA_FALLIDA = 0
	CAMPO_ACTIVO = 1
	CAMPO_INACTIVO = 0
	INDEFINIDO = -1
	LOGIN_EXISTENTE = 9
	PAGINADOR = 2
}

class CONSTANTES_CADENA {
	NO_DEFINIDO = "ND"
	FECHA_INDEFINIDA = "0000-00-00 00:00:00"
}

export const CI = new CONSTANTES_ENTERAS()
export const CC = new CONSTANTES_CADENA()